fragment MergeRequestStampFields on MergeRequest {
  id
  iid
  updatedAt
  state
  detailedMergeStatus
  autoMergeEnabled
  diffHeadSha
  approvedBy {
    nodes {
      id
    }
  }
  headPipeline {
    iid
    jobs {
      nodes {
        name
        status
        retried
      }
    }
  }
}

query MrStamps($projectPath: ID!, $state: MergeRequestState, $first: Int!, $after: String) {
  project(fullPath: $projectPath) {
    id
    mergeRequests(state: $state, first: $first, sort: UPDATED_ASC, after: $after) {
      pageInfo {
        hasNextPage
        endCursor
      }
      nodes {
        ...MergeRequestStampFields
      }
    }
  }
}
